apiVersion: apps/v1
kind: Deployment
metadata:
  name: mazaipy
  labels:
    app: mazaipy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mazaipy
  template:
    metadata:
      labels:
        app: mazaipy
    spec:
      containers:
      - name: mazaipy
        image: dimage1/mazaipy
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mazaipy
spec:
  selector:
    app: mazaipy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
