apiVersion: v1
kind: PersistentVolume
metadata:
  name: mazai-pv
spec:
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/mazaipy
    type: Directory
